### ISSUE TITLE
testapp.ui -> Class "customappwidgets.timewidget" not mapped

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#100]
The error Class "customappwidgets.timewidget" not mapped appears in a dialog window when you open [testapp.ui](https://github.com/alejandroautalan/pygubu-designer/blob/master/examples/customapp/testapp.ui).

**Comment by alejandroautalan** [comment]
This example requires to add the custom builder to the pygubu-designer.
I Added a readme file to point to the full explanation.
I think this will be enough.  Let me know.

Regards
Alejandro A.

**Comment by matecsaj** [comment]
Thank you.
