### ISSUE TITLE
add menu support to the code generator

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#103]
In the options part of the code generator, please add a drop-down for selecting the initial menu widget, if any.

When running the code generator on [menu.ui](https://github.com/alejandroautalan/pygubu-designer/blob/master/examples/toplevel_menu/menu.ui), it would be helpful if the init dunder included the following line. 
`        self.mainwindow.configure(menu=self.builder.get_object('mainmenu', self.mainwindow))`

After doing so, update the relevant [wiki page](https://github.com/alejandroautalan/pygubu-designer/wiki/Menus) and menu examples.

**Comment by alejandroautalan** [comment]
Completed in latest version.
