### ISSUE TITLE
reorder menus?

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#104]
I want to swap Help and Buy. How can I change the menu order?

![Screen Shot 2022-03-28 at 4 45 47 PM](https://user-images.githubusercontent.com/8467919/160484108-8c9e389a-030f-4e95-b6cd-c76615dec12d.png)

![Screen Shot 2022-03-28 at 4 43 17 PM](https://user-images.githubusercontent.com/8467919/160483846-41d3399a-b833-45f0-a1eb-c058bc7387b3.png)

![Screen Shot 2022-03-28 at 4 49 50 PM](https://user-images.githubusercontent.com/8467919/160484746-4aea2ca5-1800-49ca-a349-75acda4af5b2.png)

**Comment by alejandroautalan** [comment]
Hello.
Select the item you wan to move and use the options from menu  "Edit > Widget Tree" to move up or down.
O use the keys "CTRL-I" and "CTRL-k"

**Comment by matecsaj** [comment]
Sorry for overlooking that and bothering you; I added the information to a [wiki](https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Screen/_edit) page to help others. 

Please add drag-and-drop functionality to provide a faster and more intuitive way to relocate widgets.

**Comment by alejandroautalan** [comment]
> Sorry for overlooking that and bothering you; I added the information to a [wiki](https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Screen/_edit) page to help others.
Hello @matecsaj, I don't see your changes, maybe you forgot to save the page?

Regards.
Alejandro a.

**Comment by matecsaj** [comment]
Yes, I must have forgotten that step. I just re-edited the page.
