### ISSUE TITLE
tab notebook how-to question

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#113]
I studied the panes_and_notebook.ui example and am trying to do similar in my project.

I hovered over every icon in the ttk Containers, Control & Display, etc. --- I found ttk.Notebook but could not find ttk.Notebook.Tab. 

How are tabs added to a notebook; how are class ttk.Notebook.Tab children added to a class ttk.Notebook parent?

![Screen Shot 2022-04-14 at 12 16 55 PM](https://user-images.githubusercontent.com/8467919/163431085-5b7e9eba-6fcd-4b3d-a54b-7c65c0dffa9c.png)

**Comment by rdbende** [comment]
`ttk.Notebook.Tab` is in the Pygubu Helpers pane

**Comment by matecsaj** [comment]
Thank you. I see it now. Sorry to bother you with a dumb question.
