### ISSUE TITLE
a decluttering suggestion for widget ids

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#117]
Imagine for a moment:

- That a new widget has a blank id. 
- In the rare cases that the designer intends for the programmer to manipulate the widget, they give it a meaningful id name. 
- In the filter above the tree view, in addition to matching on id, match on all property fields that are text.

Benefits:

1. If the designer wanted to find all widgets that exercise a particular command or variable, then they could.

2. When the id is blank, the tree view would be more compact, with no loss of useful information. For example, "label label3: ttk.label" could become "label : ttk.label". 

3. In the property panel, it, for example, states that the class is ttk.label and the id are label2. There is no need to tell the designer twice, that it is a label.

4. The namespace would be less cluttered for the python programmer.

Today 'code script' generator produces this.

        self.frame2 = ttk.Frame(self.window_pained)
        self.label2 = ttk.Label(self.frame2)
        self.label2.configure(text="Item ID:")
        self.label2.grid(column="0", row="0", sticky="e")

Instead, it could do this for an unnamed widget that happens to be Label.

        self.frame2 = ttk.Frame(self.window_pained)
        unnamed_ttk_label_1 = ttk.Label(self.frame2)
        unnamed_ttk_label_1.configure(text="Item ID:")
        unnamed_ttk_label_1.grid(column="0", row="0", sticky="e")

And when the __init__ dunder is finished, to a certain extent, the unnamed widgets would go away and be hidden in Tkinter. If a programmer inspected the object created by the initializer, it would not be littered with label1, label2, etc., the programmer would only see the Tkinter objects that the designer explicitly named and intended for the programmer to use.

5. Today inspecting self.builder.tkvariables with a debugger is much more useful than self.builder.objects, because most of the latter is cluttered with things that the UI designer does not want the programmer to use. Widgets with blank ids could be omitted. The programmer could then focus on what they need to make use of.

6. When the programmer uses a debugger to inspect a Tkinter object, the debugger shows the class name, so you know it is, for example, a label or a button, or text variable or whatever. There is no need for the name of the object to include the words label or button.

Downsides:

1. The designer must anticipate which widgets the programmer will need to manipulate and expend labour on the extra step of giving it a meaningful name.

This [book](https://www.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515/ref=sr_1_1?crid=11ESOHBLBM7TB&keywords=don%27t+make+me+think&qid=1650211911&sprefix=don%27t+make+me+think%2Caps%2C247&sr=8-1), in particular the chapter about omitting needless words, inspired this suggestion.

**Comment by alejandroautalan** [comment]
What was done:

* A new widget has an autogenerated ID and its initial state is "unnamed".
* If the user changes the ID, the widget becomes a "named" widget.
* The user can change the state back to unnamed using the ID editor.
* Builder class now has a method "forget_unnamed". This method can be called after all the creation process to clean the builder object list and remove the unnamed objects. This method must be called manually.
* When widget is unnamed, only the class name is shown in the tree view.
* In code generation only named objects are set as class attributes. The user can change this with an option.
