### ISSUE TITLE
help menu suggestions

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#118]
If you click Help - Wiki

- it should take you [here](https://github.com/alejandroautalan/pygubu-designer/wiki) instead of [here](https://github.com/alejandroautalan/pygubu/wiki). 

If you click Help - About:

- It should show one version number. Currently, it has v0.20 and v0.25!
- pygubu should be pygubu-designer.
- The second copyright date should be 2022.

![Screen Shot 2022-04-17 at 2 45 44 PM](https://user-images.githubusercontent.com/8467919/163729806-28cb2c0e-a3d5-4c35-ac32-567f724a5655.png)

One more suggestion and I am unsure if it is even possible. On the About screen, include the version number of the pygubu run-time and warn when the currently installed version of the run-time and designer are incompatible. Perhaps also pop-up a warning every time the designer is launched with an incompatible run-time. Related to this, perhaps it could also check if the newest versions are currently installed, and notify when upgrading is possible.

**Comment by alejandroautalan** [comment]
Hello Peter, thanks for the but report.

> One more suggestion and I am unsure if it is even possible. On the About screen, include the version number of the pygubu run-time

Both number versions are shown, maybe it is not clear enough.
The "v0.20" bellow the image is the version of the run-time.
In the next line is the pygubu-designer version "v0.25"

> and warn when the currently installed version of the run-time and designer are incompatible.

The pygubu-designer package already has defined the minimal pygubu runtime to work. So it is checked at installation time.

Regards
Alejandro A.

**Comment by matecsaj** [comment]
Thank you for explaining the current situation.  A suggestion follows.

+==========+
logo

**This program**: pygubu-designer
Purpose: A visual design tool for tkinter that generates Python code for the user interface portion of your application.
Version: 0.25 (current)

**Associated program**: pygubu
Purpose: A run-time library that is required by the designer. It is optional for your application.
Version: 0.19 (upgrade)

Licence: [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html)
Copyright: your legal statement
Warranty: None.

[More info.](https://github.com/alejandroautalan/pygubu-designer)
+==========+

- Color "(current") green, and "(upgrade)" yellow if recommended, red if required.
- Don't left-align everything.
- If you are not aware, the writers of the GPL licence recommend that you assign the copyright to the Free Software Foundation. It is your choice! I'm no lawyer, don't mistake this for good advice.
