### ISSUE TITLE
please make deletion more context sensitive

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#119]
**Motivation.** It happened again; I erroneously deleted another branch of my widget tree. Expletive! Currently, the designer doesn't have 'undo'; I'm forced to revert to my last git commit and redo all my recent work.

**Relevant details.** When I edit the properties of a widget and type an extra character, I press Mac's delete key and immediately press the return key. Before the 'deletion warning dialogue' registers in my mind, I've already pressed the return key, and the designer dutifully deletes the current widget and all its children.

**Change request.** I never want to delete a widget while editing a property field. **Could you please make the delete key sensitive to the context in which it is pressed, and if somebody is editing a property field, presume that the person wants to delete the last character?** The filter field already works this way.

**Remark.** Of course, if I click a widget in the tree preview pane, and follow that by a delete, then presume I want to delete a widget. Until the undo function exists, continue to double-check with a pop-up dialogue. It works this way now, please don't lose this when making the above change.

**BTW.** I hope you don't mind that I have opened so many issues; my sincere intention is to help you make your good tool great. Thanks again for building and open-sourcing it.

**Comment by alejandroautalan** [comment]
Hello Peter,

> Change request. I never want to delete a widget while editing a property field. Could you please make the delete key sensitive to the context in which it is pressed, and if somebody is editing a property field, presume that the person wants to delete the last character? The filter field already works this way.
> Remark. Of course, if I click a widget in the tree preview pane, and follow that by a delete, then presume I want to delete a widget. Until the undo function exists, continue to double-check with a pop-up dialogue. It works this way now, please don't lose this when making the above change.

I will review the code and make deletion only available from the Tree and Preview panels.

> BTW. I hope you don't mind that I have opened so many issues; my sincere intention is to help you make your good tool great. Thanks again for building and open-sourcing it.

I'm glad that the tool is becoming more useful and that more people are using it. So please, make all suggestions you want, It really helps me to improve the project.

Regards
Alejandro A
