### ISSUE TITLE
Code generation doesn't work when anything is entered into optionmenu -> Appearance -> variable

### ISSUE THREAD

**Issue by skakunm** [alejandroautalan/pygubu-designer#125]
When I try to add any name for the variable the code won't generate. No matter what is the value of "value" or "values" field. It only generates when there is nothing in the "variable" field, and in that case it creates self.__tkvar, which is then shared between optionmenus. I'm new to pygubu-designer, so maybe I'm not using it correctly, but I guess this should work.

**Comment by alejandroautalan** [comment]
Hello @skakunm, thanks for trying pygubu and for the but report.
I will try to fix it as soon as possible.

Regards
Alejandro A.

**Comment by skakunm** [comment]
Hello Alejandro,

Thank you!

Regards,
Marko
