### ISSUE TITLE
Callbacks function and lambda

### ISSUE THREAD

**Issue by Starmania** [alejandroautalan/pygubu-designer#127]
Hey,
It is possible to use `lambda: functionName(withArgs)` in the `command` parameter... Could you allow it ?

![Code Example](https://user-images.githubusercontent.com/52313983/175765952-2bce1744-f27f-40ea-a970-503f9e976b55.png)

**Comment by Starmania** [comment]
I konw that you specifically refuse this [here](/alejandroautalan/pygubu-designer/blob/master/pygubudesigner/widgets/commandentry.py#L36) but tk and ttk allow it...

**Comment by alejandroautalan** [comment]
Hello @Starmania, thanks for trying pygubu.

The designer only allows function names in the command properties.
This makes easy the build process of the interface (connecting callbacks) and code generation.

You can achieve the same result directly configuring the callback in code.

If you are using the builder class, configure the callback after the build process:

```python
    def __init__(self, master=None):
        ...
        # Main widget
        self.mainwindow = builder.get_object("toplevel1", master)
        builder.connect_callbacks(self)

        button = builder.get_object("buttonBackRett")
        button.configure(command=lambda: controller.show_frame("Start Page"))
```

I think that you want the functionality described here #126, maybe in the future it can be implemented.

Regards
Alejandro A.

**Comment by Starmania** [comment]
Hey Alejandro,
I will try to do a fork to intregate lambda, but I need help to know the part of the code that generate commad, and how it works...
