### ISSUE TITLE
How does the builder make widgets?

### ISSUE THREAD

**Issue by GianptDev** [alejandroautalan/pygubu-designer#139]
Hi @alejandroautalan .

I'm programming a library that build ttk widgets using a set of properties but **I have a problem** _about the configuration of these widgets_.

>I'm asking to you this question because **pybugu** does use a generic logic to instance each widget and I tough it may be want I'm trying to achieve.

This problem is that the widget and the window class does not have the same configuration methods:
- **Widgets** have `pack`, `place` and `grid`.
- **Tk window** has `title`, `geometry`, ecc.

I've seen the code from **pygubu** and you mapped all the classes into a list called `CLASS_MAP` and the `_realize` method from the builder build from that list but the only configuration called methods are `configure` and `layout`.
_I can't figured out how you mapped these classes and how this list allow to build the final widget._

- How does **pygubu** configure widget properties and create them?

Thank you in advance.

**Comment by alejandroautalan** [comment]
Hello @GianptDev. I will try to answer all your questions.

>I'm asking to you this question because pybugu does use a generic logic to instance each widget and I tough it may be want I'm trying to achieve.

Yes. This generic logic is actually coded in the BuilderObject class. This base class is used to describe the tkinter widget (or helper) to be created. A BuilderObject exist for each tkinter class that can be created, eg: TTKFrame, TTKLabel, TTKSBHelperBO etc.

The Builder class is used to load an UI definition and instantiate the widgets. The process is like the following:
- Set the file to load with **builder.add_from_file()**
- Call **builder.get_object("mainwindow") to create the widget you want, in this case "mainwindow"
- Inside get_object, the builder search for the widget in the UI definition, and calls **builder._realize**

https://github.com/alejandroautalan/pygubu/blob/f97f3b5a5274058fd72d06fa5fc75d5ef0a44b8c/pygubu/builder/__init__.py#L148-L166

- First, the **_realize** method will check if the widget class to be created is in the CLASS_MAP. If it's not mapped the builder will try to load the module that will register the BuilderObject class that can create that widget.
- When the builder class is found, the **_realize** method starts to create the widget calling the builderObject methods: realize, configure, if is a container create the children widgets, and finally does layout.

https://github.com/alejandroautalan/pygubu/blob/f97f3b5a5274058fd72d06fa5fc75d5ef0a44b8c/pygubu/builder/__init__.py#L194-L221

> This problem is that the widget and the window class does not have the same configuration methods:

    Widgets have pack, place and grid.
    Tk window has title, geometry, ecc.

That is why I have to define a builder for each widget.  As I said above the BuilderObject class is the base class that hold the common logic to create a basic widget. Example, frame is a simple widget:

https://github.com/alejandroautalan/pygubu/blob/f97f3b5a5274058fd72d06fa5fc75d5ef0a44b8c/pygubu/builder/ttkstdwidgets.py#L36-L41

For more complex widgets you have to subclass and use the methods to modify the behaviour. Example, builder for Toplevel:

https://github.com/alejandroautalan/pygubu/blob/f97f3b5a5274058fd72d06fa5fc75d5ef0a44b8c/pygubu/builder/tkstdwidgets.py#L23-L130

About layout. In tkinter, a container widget can not use pack and grid managers at the same time. But it can combine one of them with place manager. Knowing that, I wanted that the designer to not add any more restrictions. So the layout code was rewritten several times.  Layout management can be seen here:

https://github.com/alejandroautalan/pygubu/blob/f97f3b5a5274058fd72d06fa5fc75d5ef0a44b8c/pygubu/builder/builderobject.py#L229-L247

My final objective with all this logic, was to be able to create my custom widgets and use them inside the designer to create my interfaces.


Regards
Alejandro A

**Comment by GianptDev** [comment]
Hi @alejandroautalan , thank you for the response and the time you've taken to write this explanation.

I will make a map list and see how it goes.
