### ISSUE TITLE
How to add custom property of a custom widget to property editor?

### ISSUE THREAD

**Issue by yucai2005** [alejandroautalan/pygubu-designer#140]
Hi @alejandroautalan ,

I am trying to use DateEntry widget from tkcalendarwidgets module in this link:
https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse

The widget is working well. However, I prefer the date format to be "dd/MM/yyyy" rather than default format "MM/dd/yy". My question is that how can I add the date_pattern property of DateEntry to property editor so that I can configure it?

Thanks in advance.

**Comment by alejandroautalan** [comment]
Hello @yucai2005 thanks for trying pygubu.

I updated the [wiki page](https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse#requirement-3---custom-widget-options) with more info and [example](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/integration_with_tkcalendar/myapp3). I hope this information helps you.

Now I'm working on the integration with other libraries like ttkwidgets, tkintertable, tksheet, awesometkinter. Therefore you will have many examples of how to adapt other widgets.

Regards.
Alejandro A.

**Comment by yucai2005** [comment]
Hi @alejandroautalan,

It works perfectly! Thank you so much for your help.
