### ISSUE TITLE
installation doesn't work on Manjaro

### ISSUE THREAD

**Issue by geeflaxx** [alejandroautalan/pygubu-designer#141]
thanks for this tool!

sadly it doesn't work.
$ pip install pygubu-designer
$ pygubu-designer

result:

![image](https://user-images.githubusercontent.com/21129138/184708269-bda24c48-756b-46b3-ae2f-cc50d7171b1a.png)

what is missing ?

**Comment by alejandroautalan** [comment]
Hello Patrick, thanks for trying pygubu.

You need tk installed on your system, try with:

    sudo pacman -S tk

On debian like systems the command is:

    sudo apt install python3-tk

Let me know.
Regards!
Alejandro A.
