### ISSUE TITLE
Exception: Class "tk.Toplevel" not mapped, when using PyInstaller 

### ISSUE THREAD

**Issue by danidask** [alejandroautalan/pygubu-designer#143]
Tring to follow the example in /examples/integration_with_pyinstaller/
It works when executed from `python myapp.py` but not from the executable `.\myapp.exe`

```
> .\myapp.exe
Traceback (most recent call last):
  File "myapp.py", line 221, in <module>
  File "myapp.py", line 26, in __init__
  File "pygubu\builder.py", line 161, in get_object
  File "pygubu\builder.py", line 208, in _realize
Exception: Class "tk.Toplevel" not mapped
[24272] Failed to execute script 'myapp' due to unhandled exception!
```

Python 3.10.5

**Comment by danidask** [comment]
pygubu-0.24
pygubu-designer-0.29
pyinstaller-5.3

Thanks @alejandroautalan

**Comment by alejandroautalan** [comment]
Hello,  I changed the spec file for pygubu 0.24.

https://github.com/alejandroautalan/pygubu-designer/blob/c470ba65312bb707b0ea78427f3f1f239623ae76/examples/integration_with_pyinstaller/myapp.spec#L6-L21

Try again and let me know.
Regards
Alejandro A.

**Comment by gwelch-contegix** [comment]
@alejandroautalan would you accept a PR to add a pyinstaller hook to this repository?

**Comment by alejandroautalan** [comment]
> @alejandroautalan would you accept a PR to add a pyinstaller hook to this repository? Or I should say the pygubu repository

Hello, @gwelch-contegix.  I think it should be in the pygubu repository. Yes I would accept it.

**Comment by gwelch-contegix** [comment]
PR submitted alejandroautalan/pygubu#266

**Comment by danidask** [comment]
Yes, it works now. Thanks for your time and for this awesome project.
