### ISSUE TITLE
Cannot Find 'pygubu-designer.exe' Within Installed Pygubu Folders

### ISSUE THREAD

**Issue by AaronCatolico** [alejandroautalan/pygubu-designer#146]
I'm trying to install Pygubu, but the '**pygubu-designer.exe**' never shows up in any of the folders after the installation  process. I first run the following commands to do the installation process:

pip install pygubu
pip install pygubu-designer

It then installs 4 main folders inside of the following path/directory:

C:\Users\Aaron\AppData\Local\Programs\Python\Python310\Lib\site-packages

pygubu
pygubu_designer-0.29.dist-info
pygubu-0.24.1.dist-info
pygubudesigner

![cannot-install-pygubu](https://user-images.githubusercontent.com/111602056/185684632-98b3c15d-b620-4152-a83f-744fd95338d1.png)

I searched all 4 of these folders to discover that the 'pygubu-designer.exe' is nonexistent.

I have 'Python 3.10.6' & 'pip 22.2.2' versions installed in the same directory. So, it seems that pygubu has attempted to be installed into the correct path/directory.

Any idea of what to do to make sure that I can download and run the 'pygubu-designer.exe' file? Thanks.

**Comment by alejandroautalan** [comment]
Hello @AaronCatolico thanks for trying pygubu.

After running the command

> pip install pygubu-designer

The executable should be in the scripts folder. In your case:

    C:\Users\Aaron\AppData\Local\Programs\Python\Python310\Scripts

Example:

![Captura de pantalla_2022-08-19_19-26-27](https://user-images.githubusercontent.com/3482471/185714992-dcca7de2-90a1-45b8-85f9-fe2f59f4e980.png)

**Comment by AaronCatolico** [comment]
Hi Alejandro,

I found it! Thank you for helping me find it! I'm about to test it out in a
few minutes. I'll let you know what I think. Thanks again!
👍👍
