### ISSUE TITLE
pygubu-designer makes Mac OS X Logoff

### ISSUE THREAD

**Issue by felipemaion** [alejandroautalan/pygubu-designer#15]
Hello, 
I've tried to install pygubu-designer via "pip install pygubu-designer" under Anaconda (conda 4.8.3).
When I run the pygubu-designer my system just logoff and goes to the Mac(10.14.6)'s logon screen.

How can I help figure it out?

**Comment by matecsaj** [comment]
I do not experience this on macOS Catalina Version V10.25.7. I installed it via pip in the Terminal.
