### ISSUE TITLE
make a Github release for version 0.29.1

### ISSUE THREAD

**Issue by itoffshore** [alejandroautalan/pygubu-designer#150]
I'm trying to build [pygubu-designer as a package for Arch Linux](https://aur.archlinux.org/packages/pygubu-designer).

never mind - found the `0.29` tag ;o)

**Comment by itoffshore** [comment]
ok - I think I still need version `0.29.1` - with `v0.29` I see:
```
You should compile the .po files in the pygubudesigner/locale directory first if you are a developer, otherwise give us feedback here: https://github.com/alejandroautalan/pygubu-designer/issues
```

**Comment by alejandroautalan** [comment]
Hello @itoffshore , thanks for trying pygubu.

I will review this problem and make a new release.

Regards
Alejandro A.

**Comment by alejandroautalan** [comment]
Uploaded new version.
Please let me know if you have any issue in the process of packaging.

Regards
Alejandro A.

**Comment by itoffshore** [comment]
Many thanks for the prompt response & updating both libraries.

The issue was `setup.py` being deprecated in `python-3.10` - building packages with `pip` is required in `3.10`. I have the latest version packaged for Arch Linux & running now:

![Screenshot_2022-09-05_00-11-42](https://user-images.githubusercontent.com/1141947/188339012-152cf63a-4559-434c-8fbe-72025f7b23bf.png)

I will probably also package the [`tk` widgets you mention here](https://github.com/alejandroautalan/pygubu-designer/wiki/Additional-widget-sets)

Your GUI Designer is great ;o)

**Comment by alejandroautalan** [comment]
Great! Thank you for supporting pygubu.
