### ISSUE TITLE
Generation of code in pygubu designer throws exception

### ISSUE THREAD

**Issue by JojoMueller** [alejandroautalan/pygubu-designer#151]
Generation of code in pygubu designer throws exception in some forms, since upgrade to pybubu 0.25 / designer 0.30.
The forms contain a menubutton in a context like this:

> ttk.Frame
   ... ttk.Menubutton
   ...... tk.Menu
   ......... tk.Menuitem.Command
   ......... tk.Menuitem.Command
			
When I press the Generate button an exception with this information occurs

> File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 386, in _code_realize
create = builder.code_realize(bmaster, uniqueid)
File "C:\Program Files\Python310\lib\site-packages\pygubu\plugins\tk\tkstdwidgets.py", line 1058, in code_realize
boparent.add_menuitem(self.wmeta.identifier, self.itemtype, properties)
AttributeError: 'TKMenu' object has no attribute 'add_menuitem'

python: 3.10.4 on win32
pygubu: 0.25
pygubu-designer: 0.30

**Comment by alejandroautalan** [comment]
Hello @JojoMueller thanks for trying pygubu and the bug report.
Please update pygubu with:

    pip3 install --upgrade pygubu

And let me know.

Regards!
Alejandro A.

**Comment by JojoMueller** [comment]
thanks for superfast fixing. Everything ok now.
