### ISSUE TITLE
Is it's possible to make some dependencies optional?

### ISSUE THREAD

**Issue by JojoMueller** [alejandroautalan/pygubu-designer#152]
I appreciate pygubu/-designer as a relatively lightweight, but flexible and powerfull GUI library and designer. It's still under developement and so there are good reasons, that the code base grows and dependencies increase. But is it really necessary to make e.g. black with it's many subdependencies mandatory? I would esteem if it's optional for those who value exceptionally well formated pyubu-generated code-snippets.

**Comment by alejandroautalan** [comment]
Hello @JojoMueller, can you elaborate more about why you don't want black as dependency?
- Is it download size?
- Distribution issue?
- Any other reason?

The pygubu core at the moment, has no dependencies (will change in next version for python versions prior to 3.9).

Code generation was requested by users so I added it in pygubu-designer.
I wanted that the designer generate readable code from scratch and
I didn't want to write a code formatter, so I pass all the work to black.

If you have an alternative to black, I can consider to change it, or make it optional.

Let me know.
Regards
Alejandro A.

**Comment by JojoMueller** [comment]
Hello Alejandro, 
As I remember, prior versions of designer were able to generate correct code, that was fine - for me. So I asked whether it's possible to make the ext. formatter optional. I just prefer, not to have too many dependencies. Black brings 5 more with it, together about 6 MB, that's not much, but only for a small feature, and who knows, how many it will be tomorrow. Ok mine is a sort of luxury problem. Thank you for your patience.
Johannes

**Comment by alejandroautalan** [comment]
Ok, I understand.
I will try with other formaters with lower size (like yapf) and see what happens.

Regards
Alejandro A.
