### ISSUE TITLE
Exception when generating code

### ISSUE THREAD

**Issue by JojoMueller** [alejandroautalan/pygubu-designer#153]
Wow, thank you for superfast solving #152. I'm perfectly happy with autopep8.
Now, when I press "Generate" in Designer missing key 'args' in dict throws an exception

> python: 3.10.4 on win32
> tk: 8.6
> pygubu: 0.26
> pygubu-designer: 0.31
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
>     return self.func(*args)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\main.py", line 857, in on_code_generate_clicked
>     self.script_generator.on_code_generate_clicked()
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\scriptgenerator.py", line 140, in on_code_generate_clicked
>     code = generator.generate_app_with_ui(uidef, target)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 165, in generate_app_with_ui
>     self.generate(
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 162, in generate
>     self._code_realize(builder, wmeta)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 395, in _code_realize
>     childid = self._code_realize(builder, childmeta)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 395, in _code_realize
>     childid = self._code_realize(builder, childmeta)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 395, in _code_realize
>     childid = self._code_realize(builder, childmeta)
>   [Previous line repeated 3 more times]
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 408, in _code_realize
>     commands = builder.code_connect_commands()
>   File "C:\Program Files\Python310\lib\site-packages\pygubu\component\builderobject.py", line 542, in code_connect_commands
>     cmd_code = self._code_connect_command(cmd_pname, cmd, callback)
>   File "C:\Program Files\Python310\lib\site-packages\pygubu\component\builderobject.py", line 586, in _code_connect_command
>     args = cmd["args"]
> KeyError: 'args'

**Comment by alejandroautalan** [comment]
Thank you @JojoMueller for your bug report.
A new version was uploaded.

Regards.
Alejandro A.
