### ISSUE TITLE
Exception when generating code

### ISSUE THREAD

**Issue by JojoMueller** [alejandroautalan/pygubu-designer#154]
Thank you for fixing #153, works fine. I've tested code generation with all my ui-forms - not the generated code itself, which I do not use currently - and found 1 remaining error.   _code_process_layout_property() throws an exception when called with pname=='uniform', in which case pvalue is None. I hope replacement of black is successfully finished then for you and you could turn to something other.

> python: 3.10.4 on win32
> tk: 8.6
> pygubu: 0.26.1
> pygubu-designer: 0.31.2
> 
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
>     return self.func(*args)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\main.py", line 858, in on_code_generate_clicked
>     self.script_generator.on_code_generate_clicked()
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\scriptgenerator.py", line 140, in on_code_generate_clicked
>     code = generator.generate_app_with_ui(uidef, target)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 165, in generate_app_with_ui
>     self.generate(
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 162, in generate
>     self._code_realize(builder, wmeta)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 395, in _code_realize
>     childid = self._code_realize(builder, childmeta)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 395, in _code_realize
>     childid = self._code_realize(builder, childmeta)
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 395, in _code_realize
>     childid = self._code_realize(builder, childmeta)
>   [Previous line repeated 1 more time]
>   File "C:\Program Files\Python310\lib\site-packages\pygubudesigner\codegen\codebuilder.py", line 404, in _code_realize
>     layout = builder.code_layout(parentid=masterid)
>   File "C:\Program Files\Python310\lib\site-packages\pygubu\component\builderobject.py", line 428, in code_layout
>     pvalue = self._code_process_layout_property(
>   File "C:\Program Files\Python310\lib\site-packages\pygubu\component\builderobject.py", line 628, in _code_process_layout_property
>     if pvalue.isnumeric() or isfloat(pvalue)
> AttributeError: 'NoneType' object has no attribute 'isnumeric'
>

**Comment by alejandroautalan** [comment]
Hello @JojoMueller thanks for the report.
Can you provide a minimal UI file example that causes that error?

Regards
Alejandro A.

**Comment by JojoMueller** [comment]
Shure. Steps to reproduce:
- open attached .ui file in designer (my most simple, but most used ui)
[toolmenu.zip](https://github.com/alejandroautalan/pygubu-designer/files/9741187/toolmenu.zip)
- generate any type of code 

Regards
Johannes
