### ISSUE TITLE
Combobox values: list not generated

### ISSUE THREAD

**Issue by iradraconis** [alejandroautalan/pygubu-designer#155]
when entering values as list
['entry 1', 'entry 2', 'entry 3']
the generated code looks like this: values="['entry 1', 'entry 2', 'entry 3']"
when giving a list, the "" should be removed. Or am I doing it wrong? I could otherwise not figure out how to give values with more than 1 word.

**Comment by alejandroautalan** [comment]
Hello @iradraconis,
Manually using code you can pass a list to the widget.
But for now, designer only supports passing a space separated string like:

    value1 value2 value3 "my long value4"

![Captura de pantalla_2022-09-30_12-28-45](https://user-images.githubusercontent.com/3482471/193305001-13cc4f56-f7a9-4b0d-a2ce-521924acc24b.png)


But I noticed that it is generating malformed code also.  I will review and prepare a fix.

Regards.
Alejandro A.

**Comment by iradraconis** [comment]
Thank you that helped as I was not aware of the correct format. There should be a tooltip with an example :)

**Comment by iradraconis** [comment]
I tried that and as you said, the code is malformed. The preview works, but the code is messed up with ""
