### ISSUE TITLE
Code Generation fails when using Chinese translations

### ISSUE THREAD

**Issue by ObaraEmmanuel** [alejandroautalan/pygubu-designer#159]
Code generation fails when locale is set to `zh_CN` or `zh_Hans`. Probably also fails for other locales which contain characters which are not valid in a python identifier. This is because translations are applied to generated class names.

**Comment by alejandroautalan** [comment]
Hello @ObaraEmmanuel, thanks for the bug report.
Can you provide a minimal UI example to reproduce the error?

Regards
Alejandro A.

**Comment by ObaraEmmanuel** [comment]
The problem is with the class name so even a single frame UI is sufficient to reproduce the issue. The default class name is what is causing the problem.
![Screenshot from 2022-10-23 09-36-21](https://user-images.githubusercontent.com/36537378/197377942-87563314-f2e5-4366-a77e-78f9cfc8faca.png)

`新项目App` is not a valid class name. But I realize now it can be changed.
