### ISSUE TITLE
tooltip for "width" in tk.Message is incorrect

### ISSUE THREAD

**Issue by AJ6CU** [alejandroautalan/pygubu-designer#162]
Tooltip says characters for with option under Specitic.  It is really pixels. Strange as some of the examples I goolged seems to say characterstoo  (but also the ones  that say wordwrap and height exist and they do not...)

**Comment by alejandroautalan** [comment]
Hello @AJ6CU thanks for the report.

Maybe you mean another widget? I don't see the error in tk.Message.

![Captura de pantalla_2022-11-19_16-45-23](https://user-images.githubusercontent.com/3482471/202868846-bf9352ac-bf5b-45a2-a70b-af0d99957979.png)


Regards
Alejandro A

**Comment by AJ6CU** [comment]
Probably not an error in true sense of word. Some of the ttk documentation (not yours) says width is in  characters. Well it is actually in pixels. Your tooltip doesn't say either way. You "could" make it clear for dummies like me that the "100" is actually pixels. 

Regards,

Mark

**Comment by alejandroautalan** [comment]
> Probably not an error in true sense of word. Some of the ttk documentation (not yours) says width is in characters. Well it is actually in pixels. Your tooltip doesn't say either way. You "could" make it clear for dummies like me that the "100" is actually pixels.

Ok, thanks for the clarification. I will add the required information.

Regards.
Alejandro A.
