### ISSUE TITLE
Can't locate pygubu-designer.exe within installed Pygubu Folders

### ISSUE THREAD

**Issue by Karoljv** [alejandroautalan/pygubu-designer#167]
I'm trying to install pygubu-designer, but the 'pygubu-designer.exe' never shows up in any of the folders after the installation process. I did:
pip install pygubu
![image](https://user-images.githubusercontent.com/93725497/203309273-c075a02b-cd1d-4cf5-b4dc-1481e849d27e.png)
pip install pygubu-designer
![image](https://user-images.githubusercontent.com/93725497/203309191-eeef2189-6d49-4534-b79a-386a574f16e6.png)

I have couple of folders with pygubu but pygubu-designer.exe is missing
![image](https://user-images.githubusercontent.com/93725497/203309636-c4d81138-4f63-497a-b343-071896e4d9a6.png)

I tried to locate it within my AppData folder but it's missing aswell
![image](https://user-images.githubusercontent.com/93725497/203310464-317be9e9-6189-4bd6-9fc2-813b7b6d30c1.png)

I have python 3.10.4 and pip 20.0.4 and python addes as system variable:
![image](https://user-images.githubusercontent.com/93725497/203311903-15a0f9a5-4322-4b84-be83-ca0461c4999e.png)

**Comment by alejandroautalan** [comment]
Hello @Karoljv thanks for trying pygubu.

As you installed it using python 3.10, designer executable should be located in:

    C:\Python310\Scripts

More info here: https://github.com/alejandroautalan/pygubu-designer/issues/146#issuecomment-1221136463

Let me know.
Regards
Alejandro A.

**Comment by Karoljv** [comment]
Could not locate pygubu-designer.exe but the command from https://github.com/alejandroautalan/pygubu/issues/222 worked!
