### ISSUE TITLE
Can't delete an item or generate code (issues on Mac Big Sur)

### ISSUE THREAD

**Issue by andreamoro** [alejandroautalan/pygubu-designer#17]
I'm on Mac OS Big Sur, and attempting to use the designer for the first time.

I've created a quick interface, with a frame nested in a toplevel, but can't delete the object regardless I use the right click (no contextual menu appears) or pressing the D button.

I believe this is a bug.
![image](https://user-images.githubusercontent.com/5256583/104049882-ff72b400-51e5-11eb-84eb-2f1e87b271ba.png)

Also the Code pane where the code should be generated doesn't seem to produce any output.

**Comment by alejandroautalan** [comment]
Hello andreamoro, thanks for trying pygubu and sorry for the late response.

- What python version are you using ?
- Did you installed python using the official installer from www.python.org ?

The actions from the edit menu are no working correctly, I will review an fix them.

> Also the Code pane where the code should be generated doesn't seem to produce any output.

No error is shown, even in the terminal console? Copy and paste, here the UI definition causing this behavior so I can analyze it.

Regards.
Alejandro A.

**Comment by andreamoro** [comment]
@alejandroautalan python has been installed pyenv and I have the 3.8.6
