### ISSUE TITLE
pygubu-designer 0.32 error: customtkinter plugin breaks with customtkinter version 5 and above

### ISSUE THREAD

**Issue by XiangQinxi** [alejandroautalan/pygubu-designer#172]
![屏幕截图 2022-12-04 184957](https://user-images.githubusercontent.com/90026267/205486454-f0f0d63f-0600-4ef1-b981-16ae1da47617.png)

**Comment by XiangQinxi** [comment]
![屏幕截图 2022-12-04 185038](https://user-images.githubusercontent.com/90026267/205486488-975a8151-8d1b-47c7-a660-14ea6ddc98c6.png)

**Comment by XiangQinxi** [comment]
info -
> pygubu : 0.27
> pygubu-designer  : 0.32

**Comment by alejandroautalan** [comment]
Hello @XiangQinxi, thanks for trying pygubu.

When do you have that error? When pygubu-designer starts?
What python version are you using?
What customtkinter version?

Regards
Alejandro A.

**Comment by alejandroautalan** [comment]
Hello, thanks for the report.   I found the problem.
The plugin breaks with the new customtkinter version 5.0

I will try to fix it ASAP.

Regards!
Alejandro A.

**Comment by JojoMueller** [comment]
About 3 month ago, I got the same error message after a pygubu-designer update. Reason was a need to change the first import directive in customwidgets.py to: 
> from pygubu.api.v1 import BuilderObject, register_widget

**Comment by kirillcisco** [comment]
Hey, something new about ctkv5 support?
pygubu-designer-0.36
pygubu-0.31
![image](https://github.com/alejandroautalan/pygubu-designer/assets/26303339/966e1c15-ebd7-4130-b524-6278dfdeb992)

**Comment by alejandroautalan** [comment]
Hello @kirillcisco,

> Hey, something new about ctkv5 support?
> pygubu-designer-0.36
> pygubu-0.31

Have you installed pillow?
I don't know why customtkinter is not enforcing pillow dependency.

Let me know if this works.

Regards

**Comment by kirillcisco** [comment]
> Hello @kirillcisco,
> 
> > Hey, something new about ctkv5 support?
> > pygubu-designer-0.36
> > pygubu-0.31
> 
> Have you installed pillow? I don't know why customtkinter is not enforcing pillow dependency.
> 
> Let me know if this works.
> 
> Regards

Thanks, @alejandroautalan 
It works well

**Comment by kirillcisco** [comment]
@alejandroautalan, but there was a problem with compatibility
```
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pygubu\builder.py", line 228, in _realize
    child = self._realize(parent, childmeta)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pygubu\builder.py", line 217, in _realize
    parent.realize(master, extra_init_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pygubu\component\builderobject.py", line 122, in realize
    self.widget = self.class_(master, **args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_frame.py", line 33, in __init__
    super().__init__(master=master, bg_color=bg_color, width=width, height=height, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 46, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['name'] are not supported arguments. Look at the documentation for supported arguments.
```

**Comment by alejandroautalan** [comment]
> @alejandroautalan, but there was a problem with compatibility

Hello @kirillcisco, thanks for your reply. I will review it ASAP.

Regards.
Alejandro A.

**Comment by Thosch42** [comment]
Is something new with the customtkinter support? I tried it also with customtkinter 4.6.3, but startup of pygubu-designer fails.

**Comment by alejandroautalan** [comment]
Updated pygubu and designer to support customtkinter 5.2.2

Please install all dependencies of customtkinter.
Or install using:

    pip install pygubu-designer[customtkinter]

Regards.
