### ISSUE TITLE
Preview repaint - size and selection issue

### ISSUE THREAD

**Issue by SiL3NC3** [alejandroautalan/pygubu-designer#173]
Why is the preview always being rendered in a smaller size, as the widgets are needing, which hides the area being edited.
Can this be prevented in any way, by giving a parent widget a size?

Also selection (red rectangle) is not selecting the currently selected item of the treeview...

**Comment by jrezai** [comment]
Hi @SiL3NC3 , try setting the 'geometry' value for the toplevel widget.
![size](https://user-images.githubusercontent.com/45316730/205930862-3c207bc5-d965-4837-aac1-3c6dbc28edb9.png)

Regarding your second question (red rectangle and the treeview item), is that happening during design-time or when previewing the window via F5? Can you share a screenshot?

**Comment by SiL3NC3** [comment]
Only during design time.
The preview is always being re-renders, when an property option is changed, or even a character of the text-property is changed.
It is always shrinking and not keeping the geometry setting of the toplevel widget.
Given is height 1100 and a width with 1000, but it is definitely smaller...
Geometry is not set. I'm thinking, this is the same setting!?

Starting the window with F5 is working nearly as expected.
The window is starting with the min-size, not the defined size via height and width.

Will give the geometry setting a try..

**Comment by jrezai** [comment]
>  The preview is always being re-renders, when an property option is changed, or even a character of the text-property is changed.
> It is always shrinking and not keeping the geometry setting of the toplevel widget.

By default, Tkinter automatically adjusts the size of the window to match its contents. It's just the nature of Tkinter.
So that means if you manually resize the preview with your mouse and then later make changes (like editing text), Pygubu Designer will re-create the design preview and it will go back to its original size. That's normal. To prevent that from happening, use the geometry setting.

> Is there really a difference or can the geometry possibly maintained with the settings for height and width?

Using geometry is the way to go if you want to set a width/height for a toplevel widget. I almost never set the width/height of widgets unless I'm using the place() manager.

**Comment by SiL3NC3** [comment]
Thank you for clarifying this!

Another short question, I cannot get the column headers sticky, when using the ScrollbarHelper or even the Scrollbar widget.
I cannot add the Scroll to a TreeView as child element... Is there a reason for this?
And on the other hand, how to bind the Scrollbar events to a treeview?

Maybe dumb questions, but I'm still struggling with... 
So any hint really appreciated.

**Comment by alejandroautalan** [comment]
Hello @SiL3NC3, thanks for trying pygubu.

> Another short question, I cannot get the column headers sticky, when using the ScrollbarHelper or even the Scrollbar widget with TreeView.

The treeview has by default all columns with minwidth=20 and stretch=True.  When you expand a column header, the treeview recalculates the size for all stretchable columns and tries to fit all columns in the view. This, some times, makes the scrollbars disapear when using ScrollbarHelper, or you can't scroll, if you are using manually connected scrollbars.

To avoid that, give to the columns a different minwidth. Se the example [here](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/treeview/demo2).

> I cannot add the Scroll to a TreeView as child element... Is there a reason for this?

The treeview is not a container of other widgets.

> And on the other hand, how to bind the Scrollbar events to a treeview?

The example mentioned above shows this. The second treeview has scrollbars configured with code.

Let me know if you have more questions.

And Thank you @jrezai for all the correct explanations.

Regards!

**Comment by SiL3NC3** [comment]
Thank you guys, for you comments. I appreciate it!

Can I use the Designer to create a Scrollbar (via the Helper) with is having sticky column headers?
In my test, on scrolling, the headers are also scrolling and getting hidden.
The example with the code is having sticky headers. Is there an option for this behavior in ScrollbarHelper?
Nothing found so far...

**Comment by SiL3NC3** [comment]
Added animation, what I mean with column headers getting hidden...
![Animation](https://user-images.githubusercontent.com/694970/206119230-974944b0-bdfd-4529-afc6-bd6605be4685.gif)

**Comment by alejandroautalan** [comment]
> Can I use the Designer to create a Scrollbar (via the Helper) with is having sticky column headers?
> In my test, on scrolling, the headers are also scrolling and getting hidden.
> The example with the code is having sticky headers. Is there an option for this behavior in ScrollbarHelper?
> Nothing found so far...
> Added animation, what I mean with column headers getting hidden...

I think that you are using a ScrolledFrame? Post your UI file or a screenshot of your widget tree.

The example that I posted is using ScrollbarHelper.


> And is there a way to get entries bound in a TreeView within the designer?
> To can test large amouts of entries without tweaking the code.
> Another thing. Is is possible to import a designer project by a code block/file (not the saved xml.ui file)
> A nice thing would be, to can create some kind of "code-only" blocks, that will generate a function for creating that related widgets section. For example, every tab of a Tabs widget could be generated with a own function for more readability...

Your can make a custom code block widget.  
But the "custom widget" area is not finished yet (some docs [here](https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse) ), but I can try to make a quick code block so you can experiment.


Regards

**Comment by SiL3NC3** [comment]
OMG, I totally missed playing around with the ScrolledFrame!
I think this will feed my requirements.
Will give this a quick try. Good hint. ;)

Thank you for you assistance.
