### ISSUE TITLE
Cannot select grid layout for frame except first level frame and LabelFrame.

### ISSUE THREAD

**Issue by TarisMarh** [alejandroautalan/pygubu-designer#18]
I can set layout "pack" or "place", but cannot set "grid" if frame is not Toplevel or first level child of Toplevel. It's very sad because "grid" layout is most usable to build complex interfaces.

**Comment by alejandroautalan** [comment]
Hello TarisMarh, thanks for trying pygubu.

> I can set layout "pack" or "place", but cannot set "grid" if frame is not Toplevel or first level child of Toplevel. It's very sad because "grid" layout is most usable to build complex interfaces.

You can combine Frames with different managers in any level to create the layout you want. The procedure is described below.

Inside a container widget, **the manager types available for select will depend on the manager type choosed for the first child** widget.
This restriction comes from the tk library. It is not possible to use grid and pack managers at the same time in a container widget.
For example:
- Add a ttk.Frame named '**mainframe**' (a container widget)
- Inside mainframe add a ttk.Label, **label1**. At this point, you can choose between three manager options: pack, grid, and place.
- You choose pack manager for **label1**. Then, all other widget you add to **mainframe** will be packed (or placed)
- If you choose grid manager for **label1**, then all other widget you add to **mainframe** will be gridded (or placed)

Small video example to show the procedure

![pygubu-designer-grid](https://user-images.githubusercontent.com/3482471/97789018-0bb21380-1b9c-11eb-9bb5-c3cbfc2073d7.gif)

I know it can be confusing at first, and maybe I will change this behavior in the future. #4

Let me know if this helps.
Regards!
Alejandro A.
