### ISSUE TITLE
pathchooser widget requires file to exist when code snipet or widget selected

### ISSUE THREAD

**Issue by AJ6CU** [alejandroautalan/pygubu-designer#184]
Hi,

I used the demo code:
https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/pathchooserdemo

Set the "mustexist" to false in pygubu.  Works when I generate an application. However, when generating a code snipet, and running it pops a message box saying file must exist.  

Also tried generating a "widget" and from within pycharms, get the error message 'PathchooserdemoWidget' has no attribute pack. Less worried about this latter issue as I "think" that pycharm is just complaining that it needs a container widget and it can't be parented to the "root"

Mark

**Comment by AJ6CU** [comment]
I believe the problem is this code in the widget (around line 146)
--
            fdoptions.pop("mustexist")
            fname = filedialog.askopenfilename(**fdoptions)
--

That needs to be something like
if( fdoptions.pop("mustexist")=='True' :
            fname = filedialog.askopenfilename(**fdoptions)
else:
            fname = filedialog.saveasfilename(**fdoptions)

Have not tried this. There is also some confusion in doc whether it is "True", True, or "true".   Looks like the pattern is "True".  I have no idea why the UX driven by the XML file works as expected...  Must be difference between generated code and the interpreted?

Best

Mark

**Comment by AJ6CU** [comment]
This appears to 'work" for me.  Noticed that I corrected the typo" filedialog.saveasfilename to filedialog.asksaveasfilename. 
[pathchooserinput.zip](https://github.com/alejandroautalan/pygubu-designer/files/10326215/pathchooserinput.zip)

Best
Mark

**Comment by alejandroautalan** [comment]
Hello @AJ6CU, sorry for the late response.

I think you found the solution. I will apply your changes and do some tests ASAP.

Thank you!
Alejandro A.

**Comment by alejandroautalan** [comment]
> There is also some confusion in doc whether it is "True", True, or "true". Looks like the pattern is "True". I have no idea why the UX driven by the XML file works as expected... Must be difference between generated code and the interpreted?

I will review this too.

**Comment by AJ6CU** [comment]
I think there is still a problem here. It appears that pygubu-designer is generating (when I ask for generation of a code snipet) a string of either "true" or "false" for the mustexist parameter.  However, the pathchooser widget assume a boolean and tests for True or False.   I tested this out by using "false" (from designer), and still got the open file dialog. When I edited the generated code and replaced "false" with False, I got the saveas box as expected.

**Comment by alejandroautalan** [comment]
> I think there is still a problem here. It appears that pygubu-designer is generating (when I ask for generation of a code snipet) a string of either "true" or "false" for the mustexist parameter. However, the pathchooser widget assume a boolean and tests for True or False. I tested this out by using "false" (from designer), and still got the open file dialog. When I edited the generated code and replaced "false" with False, I got the saveas box as expected.

Hello @AJ6CU,  Did you try this with the master branch? I think this is fixed but not released yet.
You can install it in a virtual environment with the following:

    pip install git+https://github.com/alejandroautalan/pygubu
    pip install git+https://github.com/alejandroautalan/pygubu-designer

Let me know if you can test it.
Regards
