### ISSUE TITLE
Creating a drop down menu

### ISSUE THREAD

**Issue by dakilla-ctrl** [alejandroautalan/pygubu-designer#190]
I am trying to create a dropdown menu. Its done but I cant' generate the code. I get the prompt to generate widget. I tried to generate widget but the option is blank. I also tried adding a frame as a root for the menu widget but it turns out the menu widget doesn't fit in any container. pls help. screenshots below
![Screenshot (60)](https://user-images.githubusercontent.com/69983641/216847271-f93f37ed-59cb-499e-a119-914bed822abd.png)
![Screenshot (62)](https://user-images.githubusercontent.com/69983641/216847284-c133e7d2-7473-4987-aa6b-3202d326bf79.png)

**Comment by alejandroautalan** [comment]
Hello @dakilla-ctrl thanks for trying pygubu.
The code generation template considers that menues will be associated with a toplevel container.
Therefore go to Containers tab and just add a Toplevel widget.

Regards
Alejandro A.

**Comment by dakilla-ctrl** [comment]
Thank you  @alejandroautalan  for responding so fast. It worked, I was able to generate the code
