### ISSUE TITLE
checkbutton bug

### ISSUE THREAD

**Issue by biroman** [alejandroautalan/pygubu-designer#194]
I have two label frames with the first one having 4 checkbuttons, and the other label frame having 2 checkbuttons.

If I click the first or  second checkbuttons, the first 2 checkbuttons in the label frames gets checked.

I tried moving checkbuttons out of frame, still same thing. Changed their names too.

If all checkbuttons are outside a label frame, this doesn't happen.

**Comment by alejandroautalan** [comment]
Hello @biroman, thanks for trying pygubu.

If you copied and pasted the checkbuttons, make sure they have different variable names defined in the "variable" property.

Let me know.
Regards

**Comment by biroman** [comment]
> Hello @biroman, thanks for trying pygubu.
> 
> If you copied and pasted the checkbuttons, make sure they have different variable names defined in the "variable" property.
> 
> Let me know. Regards

Thanks for quick respons!

I tried even deleting the checkbutton and created new ones without copy, same result.
