### ISSUE TITLE
Please add dark mode for editor.

### ISSUE THREAD

**Issue by peter58228** [alejandroautalan/pygubu-designer#202]
Please add dark mode for editor. 
Dark mode is very important for people with vision problems.

**Comment by Melechtna** [comment]
> Please add dark mode for editor. Dark mode is very important for people with vision problems.

Second this, my eyes are bleeding

**Comment by alejandroautalan** [comment]
Version v0.39 adds some dark themes based on ttkbootstrap.  I hope this helps to solve this issue.

**Comment by peter58228** [comment]
Thanks a lots.
________________________________
发件人: Alejandro Autalán ***@***.***>
发送时间: 2024年4月17日 9:23
收件人: alejandroautalan/pygubu-designer ***@***.***>
抄送: peter58228 ***@***.***>; Author ***@***.***>
主题: Re: [alejandroautalan/pygubu-designer] Please add dark mode for editor. (Issue #202)


Version v0.39 adds some dark themes based on ttkbootstrap. I hope this helps to solve this issue.

―
