### ISSUE TITLE
Program crashes when scaling top-frame quickly

### ISSUE THREAD

**Issue by BJuneTheLegend** [alejandroautalan/pygubu-designer#220]
Program crashes when changing size of  top-frame quickly.

I cannot find a way to reproduce or remember exactly what I did but it happened to me twice doing the same thing.
[video](https://imgur.com/a/dLXkGp8)

**Environment**
 - OS: Windows 11
 - Python version: Python 3.11
 - Designer version: pygubu-designer v0.10

**Comment by alejandroautalan** [comment]
Hello @BJuneTheLegend, thanks for trying pygubu.

Please install the latest version 0.36 using pip:

    pip3 install pygubu-designer

Or use github tags from [here](https://github.com/alejandroautalan/pygubu-designer/tags). Github releases page is not up to date.

Try it and let me know.
Regards
Alejandro A.

**Comment by BJuneTheLegend** [comment]
> Hello @BJuneTheLegend, thanks for trying pygubu.
> 
> 
> 
> Please install the latest version 0.36 using pip:
> 
> 
> 
>     pip3 install pygubu-designer
> 
> 
> 
> Or use github tags from [here](https://github.com/alejandroautalan/pygubu-designer/tags). Github releases page is not up to date.
> 
> 
> 
> Try it and let me know.
> 
> Regards
> 
> Alejandro A.

Okay. I will let you know if the crash happens again. Thanks!
