### ISSUE TITLE
CTkCanvas is missing in CustomTkinter Widgets

### ISSUE THREAD

**Issue by Thosch42** [alejandroautalan/pygubu-designer#240]
Hi Alejandro,
first things first: Thanks for your amazing work!
And also thanks, that you get CustomTkinter support running.
There is one thing I'm missing in the Widgets Ribbon from CustomTkinter: The CTkCanvas.

It would be nice if you could implement it.

Best regards,
Thomas

**Comment by alejandroautalan** [comment]
Hello @Thosch42, thanks for trying pygubu.
I'm glad that it is useful to you.

> There is one thing I'm missing in the Widgets Ribbon from CustomTkinter: The CTkCanvas.

I'll add it as soon as possible.

Regards
Alejandro A.

**Comment by alejandroautalan** [comment]
Fixed in v0.39
