### ISSUE TITLE
Pygubu-designer missing weight options 

### ISSUE THREAD

**Issue by QueenZombie** [alejandroautalan/pygubu-designer#241]
**Describe the bug**
In layout with grid selected, there are no options to add grid 0 option or grid column 1 option

**To Reproduce**
1. Add Frame, set to gride and add sticky nsew
2. Add Label, 
3. Click on layout
4. Click grid option
5. See error

**Expected behavior**
Able to modify grid row weight, and column weight

**Screenshots**
![image](https://github.com/alejandroautalan/pygubu-designer/assets/156029235/71272f0d-f9b8-40fe-8d91-369807963ec2)

This is what I need 
![image](https://github.com/alejandroautalan/pygubu-designer/assets/156029235/445d2b12-6f5e-4784-bec6-6f09966389bf)

**Your Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: Python 3.11.5
 - This program: pygubu-designer version: 0.38
 - Associated program: pygubu version: .34

**Additional context**

**Comment by alejandroautalan** [comment]
Hello @QueenZombie, thanks for trying pygubu.

Since the grid manager allows configuring options for the "all" index of rows and columns, its configuration was moved to the parent widget.
Go to parent > Layout > Options for Grid container
There you will find the configuration options you need.

![Captura desde 2024-03-06 23-04-32](https://github.com/alejandroautalan/pygubu-designer/assets/3482471/1637ce27-5532-4883-8d2b-c072d145b6f9)

Regards
Alejandro A.

**Comment by QueenZombie** [comment]
Thanks for the quick response! I'm still not able to make the boxes stretch. Do you know what version this pygubu-designer is? 
![image](https://github.com/alejandroautalan/pygubu-designer/assets/156029235/3e6fac76-fb4b-4389-be06-c83d5bafe02f)

**Comment by alejandroautalan** [comment]
> Thanks for the quick response! I'm still not able to make the boxes stretch. Do you know what version this pygubu-designer is? ![image](https://private-user-images.githubusercontent.com/156029235/310729721-3e6fac76-fb4b-4389-be06-c83d5bafe02f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODI1NTAsIm5iZiI6MTcwOTc4MjI1MCwicGF0aCI6Ii8xNTYwMjkyMzUvMzEwNzI5NzIxLTNlNmZhYzc2LWZiNGItNDM4OS1iZTA2LWM4M2Q1YmFmZTAyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwMzMwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGFjMjNkZGVlY2NkZjdhNmRmOTE5ZWQzZjE4NmNkZWVmNTJlNzdmNDc4ZGVlZjQ3YTE5NDJhNjI3ZWQ1YWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UzGs4YU47Pl4LpKuwegiwVSWGP-mvRZpSSWP4GS1xRo)

It's pygubu-designer 0.23

    pip install pygubu-designer==0.23 pygubu==0.19

Can you post the link of that video. I would like to see it.

**Comment by QueenZombie** [comment]
https://m.youtube.com/watch?v=yloK_3Eba-o

I'm trying to follow directions in the video at timestamp: 4:24
