### ISSUE TITLE
Missing tab 'Custom Widgets' in preferences

### ISSUE THREAD

**Issue by k-i-din** [alejandroautalan/pygubu-designer#245]
**Describe the bug**
"Custom Widgets" Tab does not exist when opening Preferences. As described within this example:  [https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse](url)

**To Reproduce**
1. Click on 'Edit'
2. Click on 'Preferences'
3. Look for tab 'Custom Widgets'

**Expected behavior**
Tab 'Custom Widgets' should exist and offer options to register custom Widgets.

**Screenshots**
![image](https://github.com/alejandroautalan/pygubu-designer/assets/129302348/e7398abc-9618-4349-9ab8-65a1829785b1)

**Your Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.11
 - Pygubu version: 0.35
 - Designer version: 0.39.1

**Additional context**
Was working in version 0.38

**Comment by jrezai** [comment]
Custom Widgets has moved to a new spot; it's now in the Project menu, under Settings.
There are some big differences between 0.38 and 0.39.1

Check out this video which explains the differences:
https://youtu.be/k9T8rq10Vuo

**Comment by alejandroautalan** [comment]
Hello @k-i-din, thanks for trying pygubu.

As Jobin said above, the "Custom Widgets" section from Preferences was moved to the "Project Settings" dialog.
There were many changes in the designer. I will try to update the docs and make some videos.

Regards
Alejandro A.

**Comment by k-i-din** [comment]
Hi, thanks for your quick response and developing this great tool. And also thanks to Jobin for creating the tutorial videos.
