### ISSUE TITLE
CTkFrame not resizable since pygubu 0.33

### ISSUE THREAD

**Issue by KarritPrimorph** [alejandroautalan/pygubu-designer#259]
Since pygubu 0.33 customtkinter.CTkFrames are no longer resizable. It seems like pygubu >= 0.33 ignores the following lines in UI file:
 ```
<containerlayout manager="grid">
          <property type="col" id="0" name="weight">1</property>
          <property type="row" id="0" name="weight">1</property>
        </containerlayout>
```
And this bug makes all my UI based on customtkinter in pygubu 0.32 broken and useless.   Manual additions of these lines to UI file does not help.

In pygubu-designer, options for columns and rows weight configuration in Layout tab are missing. However ttk.Frames work fine (see screenshots). 

**Screenshots**
This is what I expect:
![obraz](https://github.com/alejandroautalan/pygubu-designer/assets/144039466/de6ef74e-5ff3-4c95-8577-95a9881b67ab)

This is what I get when CTkFrame is used instead of ttk.Frame:
![obraz](https://github.com/alejandroautalan/pygubu-designer/assets/144039466/30dd7de2-5c9b-42a8-a1eb-9ad2db16c188)

My Environment 
 - Kubuntu 24.04/Opensuse 15.5
 - Python 3.12
 - Pygubu: 0.35.2
 - Designer 0.39.3

**Comment by alejandroautalan** [comment]
Hello @KarritPrimorph thanks for the bug report.

Please install pygubu version 0.35.3 and let me know if this resolves the issue.

Regards
Alejandro A.

**Comment by KarritPrimorph** [comment]
Hello,
I've already tested CTkFrames in pygubu 0.35.3 and designer 0.39.3. Now they both work fine. Perfect! 
Thank you very much for fixing the bug.
Best regards,
Marcin
