### ISSUE TITLE
CTKEntry text values not working

### ISSUE THREAD

**Issue by AlanC5432** [alejandroautalan/pygubu-designer#266]
**Describe the bug**
When placing a CTKEntry text value in the properties, The Preview does not show it.

When generating code the following line is present:

ctkentry1.configure(text='ctkentry1')

and the following Value Error is given during runtime:
ValueError: ['text'] are not supported arguments.

uses text= to set the text value when generating code

To Fix the issue I need to change text= to placeholder_text=
as that is the correct property to use in CTKEntry.

ctkentry1.configure(placeholder_text='ctkentry1')

**To Reproduce**
1. Create a CTkToplevel, CTkFrame, CTkLabel and CTKEntry
2. Click on text property of CTkEntry widget and ensure there is some text in the box
3. Preview does not show any text
4. Generate code

**Expected behavior**
running python should show a window with a label and a text box

**Screenshots**

**Your Environment (please complete the following information):**
 - OS: [Windows 11]
 - Python version: [Python 3.12]
 - Pygubu version: [pygubu 0.35.4]
 - Designer version: [pygubu-designer 0.39.3]

**Additional context**
The property of a CTKEntry widget should be placeholder_text and not text.

**Comment by alejandroautalan** [comment]
Hello @AlanC5432, thanks for the bug report.

Fixed in pygubu v0.35.5

Regards.
Alejandro A.
