### ISSUE TITLE
Canvas with Scrollbar

### ISSUE THREAD

**Issue by Jalkhov** [alejandroautalan/pygubu-designer#31]
Hi, I would like to know how I can configure a Canvas so that the scrollbars appear when what is drawn on it, exceeds the size it has, I tried using ScrolledFrame but it doesn't work.

**Comment by alejandroautalan** [comment]
Hello Jalkhov.
For the scrollbars you can use the pygubu Scrollbarhelper.
Then you just need to update the canvas scroll region after drawing on it.

I added a example [here](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/canvas/canvas-scrollregion). The UI setup (simplified) is this:

```
toplevel
  mainframe
    button
    scrollbarhelper
      canvas
```
And the code to update the canvas scroll region is on the function _btn_draw_clicked_:

```python
    def btn_draw_clicked(self):
        figures = ['square', 'cross', 'circle', 'triangle']
        figure = random.choice(figures)
        self._draw_figure(figure)
        
        # Update Canvas scroll region
        bbox = self.canvas.bbox('all')
        self.canvas.configure(scrollregion=bbox)
```

Let me know if this helps.

Regards
Alejandro A.

**Comment by Jalkhov** [comment]
Dang I had completely forgotten about the scrollbarhelper >.> It works fine Alejandro, thanks :D
