### ISSUE TITLE
Example helloworld.ui does not work

### ISSUE THREAD

**Issue by rudi48** [alejandroautalan/pygubu-designer#32]
helloworld.ui 
Error message:
not well-formed (invalid token): line 74, column 89

**Comment by alejandroautalan** [comment]
Hello rudi48, thanks for trying pygubu.
Please give me more information about your problem:
- What OS are you running?
- What Python version ?
- What command or situation is generating the reported error?

The correct procedure to test the helloworld example is:

- Install pygubu-designer

        pip3 install pygubu-designer

- Download the example files [helloworld.ui](https://github.com/alejandroautalan/pygubu-designer/raw/master/examples/helloworld/helloworld.ui
) and  [helloworld.py](https://github.com/alejandroautalan/pygubu-designer/raw/master/examples/helloworld/helloworld.py)

- Open a terminal in the folder where you downloaded the files. Run the example with:

        python3 hellowold.py


Regards
Alejandro A.

**Comment by rudi48** [comment]
Hello Alejandro,

Thank you very much for your answer and the good program.
Now helloworld.py and pygubu-designer helloworld.ui works as expected.

OS is MacOS Mojave.

I am very sorry.
It was my fault. I downloaded the HTML version of the file helloworld.ui.

Best regards, Rudi
