### ISSUE TITLE
codebuilder>code script puts commands in wrong position, does not run function

### ISSUE THREAD

**Issue by MKSanic** [alejandroautalan/pygubu-designer#34]
what it currently does:
`button = tk.Button(self.parent)`
`button.configure(command=buttonCommand)`
what it should do:
`buttn = tk.Button(self.parent,command=buttonCommand)`

for some reason, without defining which function the button uses when initializing it, it doesn't run the command

**Comment by alejandroautalan** [comment]
Hello MKSanic, thanks for trying pygubu and sorry for the late reply.
- What OS are you using?
- Python version ?
- pygubu-designer version?
- Which template are you using to generate code? "Code Script" or "Custom Widget"?
- Can you provide a minimal UI example and code to test the issue?

Meanwhile I will try to reproduce the issue.

Regards
Alejandro A.

**Comment by MKSanic** [comment]
uh, the issue is not replicating itself now. sorry for the inconvenience caused. thank you for responding

**Comment by irmoah80** [comment]
Hi , I have problem in set a command for ctkbtn, when is run generated code , btn function does not run :
`Missing callbacks for commands: ['search']`
In this case , I set `searchbtn` for command of CTKButton , in Pygubu Designer v0.39.3

**Comment by irmoah80** [comment]
solved :)
