### ISSUE TITLE
Cannot add more than 2 Frames to a Toplevel

### ISSUE THREAD

**Issue by MoeinMavini** [alejandroautalan/pygubu-designer#37]
Version: pygubu-designer v0.17
Microsoft windows

How to reproduce:
Make a toplevel then make multiple Frames for that toplevel.
After 2 frames, frames are thrown out of toplevel and displayed separately.

I could change .ui file manually and it was displayed in designer correctly.

**Comment by alejandroautalan** [comment]
Hi Moein, how are you?

Currently pygubu-designer only allows 2 children for the Toplevel widget. These children can be a Frame and a ToplevelMenu (helper).
This restriction comes from the time when pygubu-designer only supported the grid manager.

But now that it supports all managers, maybe this restriction should be removed?
What do you think?

I am going to carry out more tests to analyze whether or not it is appropriate to remove this restriction.
Let me know.

Regards
Alejandro A.

**Comment by MoeinMavini** [comment]
Hi, thanks hope your are doing fine.

Well i am not a tkinter pro but as a programmer i think that in a programming tool a crippling limitation is worst than a not great UX, So i think removing the limitation is a priority over grid not showing properly if user does something that should not be done.

Grid not showing properly could be an new issue after removing the limitation, solution could be limit if toplevel is grid.

Tell me if i can help in anyway.
