### ISSUE TITLE
Grid is not properly working with generating code script.

### ISSUE THREAD

**Issue by blutics** [alejandroautalan/pygubu-designer#39]
when grid is set on an item with expanding itself through height and width, it has to have weight.
And actually it should be on the container have the item.

for example,
self.button37 = ttk.Button(self.frame16)
self.button37.configure(text='button37')
self.button37.grid(column='0', row='0', sticky='nsew')
self.button37.columnconfigure('0', weight='1')

in this situation, instead of columconfiguring on button37,
it should be on frame16.

**Comment by blutics** [comment]
when grid is set on an item with expanding itself through height and width, it has to have weight.
And actually it should be on the container have the item.

for example,
self.button37 = ttk.Button(self.frame16)
self.button37.configure(text='button37')
self.button37.grid(column='0', row='0', sticky='nsew')
self.button37.columnconfigure('0', weight='1')

in this situation, instead of columconfiguring on button37,
it should be on frame16.

**Comment by alejandroautalan** [comment]
Hello blutics, thanks for trying pygubu and for the bug report.
I will fix it ASAP.

Regards
Alejandro A.

**Comment by jrezai** [comment]
@alejandroautalan  On a similar note, I noticed that if you change the Grid column weight, it will change the Grid column weight for **all** of the widgets that have the same parent. Grid row weight, however, doesn't have that issue.
For example:

```
> Top Level:
>   -> Frame1
>      -> Button1
>      -> Button2 (if you change Grid column weight to 1, then Button1 will automatically also get a Grid column of weight of 1)
```
I'm not sure if this is related to the same problem described above, but it's also a bug.
Thanks.
