### ISSUE TITLE
Unable to select grid manager for label and entry widgets.

### ISSUE THREAD

**Issue by koutoftimer** [alejandroautalan/pygubu-designer#4]
[quiz.zip](https://github.com/alejandroautalan/pygubu-designer/files/4760751/quiz.zip) here quiz.ui file I'm using. 

I can select grid manager for `Frame` widgets, but unable to do so for `Label` and `Entry` widgets.

**Comment by alejandroautalan** [comment]
Hi Ruslan, thanks for trying pygubu.

Inside a container widget, the manager types available for select will depend on the manager type choosed for the first child widget.
This restriction comes from the tk library. It is not possible to use grid and pack managers at the same time in a container widget.
For example:
- Add a ttk.Frame named '**mainframe**' (a container widget)
- Inside mainframe add a ttk.Label, **label1**. At this point, you can choose between three manager options: pack, grid, and place.
- You choose pack manager for **label1**. Then, all other widget you add to **mainframe** will be packed (or placed)
- If you choose grid manager for **label1**, then all other widget you add to **mainframe** will be gridded (or placed)

You can combine Frames with diferent managers to create the layout you want.

Regards
Alejandro A.

**Comment by koutoftimer** [comment]
Steps to reproduce:

1. Download and unzip `quiz.zip`
2. From Pygubu-Designer select File -> Open -> Select `quiz.ui` file
3. Unfold objects in Objects tree
4. Select "app" and "question" frames to ensure they have selected `grid` layout
5. Select "label" and "entry" widgets to ensure you are UNABLE to select grid layout. There are no such optoin.

![pygubu-label-layout](https://user-images.githubusercontent.com/4004825/84697773-68978f00-af57-11ea-88b8-dbb126f4865a.png)

**Comment by koutoftimer** [comment]
If I'm switching app: ttk.Frame with tk.TopLevel issue with grid layout remains the same.

**Comment by alejandroautalan** [comment]
Hello, now I understand the problem. I will add a better way to inform and change the layout of all the children of a container.
For now, following the example, to switch to grid layout:
- Cut (or Delete) 'entry_1'
- Change 'label_question' to grid layout
- Click on 'question' frame to select it.
- Paste (or add again) 'entry_1', it will be added with grid layout.

Remember, the layout type of the first child determines the layout for all children of the current container.

Regards
Alejandro A

**Comment by koutoftimer** [comment]
@alejandroautalan I'm new to Tkinter, but, IMHO, you aren't able to use different geometry managers for some of widgets under `Tk` or `Toplevel`, so why not to lock that ability for top level widget only?

In that way, you need to change only one place and all other will have it's value copied and not editable.

From https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/tkinter.pdf
> Although there are three different “geometry managers” in _Tkinter_, the author strongly prefers the
`.grid()` geometry manager for pretty much everything. This manager treats every window or frame as a table—a gridwork of rows and columns.

**Comment by alejandroautalan** [comment]
I add a small video example to show the procedure.

> Inside a container widget, the manager types available for select will depend on the manager type choosed for the first child widget.
> This restriction comes from the tk library. It is not possible to use grid and pack managers at the same time in a container widget.
> For example:
> 
>     * Add a ttk.Frame named '**mainframe**' (a container widget)
> 
>     * Inside mainframe add a ttk.Label, **label1**. At this point, you can choose between three manager options: pack, grid, and place.
> 
>     * You choose pack manager for **label1**. Then, all other widget you add to **mainframe** will be packed (or placed)
> 
>     * If you choose grid manager for **label1**, then all other widget you add to **mainframe** will be gridded (or placed)
> 
> 
> You can combine Frames with diferent managers to create the layout you want.

![pygubu-designer-grid](https://user-images.githubusercontent.com/3482471/97789018-0bb21380-1b9c-11eb-9bb5-c3cbfc2073d7.gif)
