### ISSUE TITLE
Tk is opening two windows

### ISSUE THREAD

**Issue by sblisesivdin** [alejandroautalan/pygubu-designer#43]
I couldn't manage to repeat the process how it occurred but, at a point my generated code script changed the line

`self.toplevel1 = tk.Tk() if master is None else tk.Toplevel(master)`

with this one

`self.toplevel1 = tk.Toplevel(master, container='false')`

and then Tk starts to open two windows, the original one and an empty one.

![Screenshot 2021-08-24 110133](https://user-images.githubusercontent.com/10999129/130579956-50fe867a-a255-49d8-91b3-8abd54ce263b.png)

**Comment by alejandroautalan** [comment]
Hello Sefer, thanks for trying pygubu.

This is a tkinter issue.
Every tkinter program needs a "root" window, this is created with tkinter.Tk()
A widget (or in this case the Toplevel) can not be created without a root window.
So, the following code will create two windows if master is None:

    self.toplevel1 = tk.Toplevel(master, container='false')

The little empty window shown in the screenshot is the root window created automatically.
The root window and the Toplevel are very similar, so **for the first window** is ok to write:

    self.toplevel1 = tk.Tk()

Or the more generic code:

    self.toplevel1 = tk.Tk() if master is None else tk.Toplevel(master)
    
A better explanation is [here](https://stackoverflow.com/a/29655755)

Let me know.
Regards

Alejandro A.

**Comment by alejandroautalan** [comment]
Hello Sefer.

I see your point. When you set a property that is specific of tk.Toplevel
(like container="false") pygubu-designer only generates:

    self.toplevel1 = tk.Toplevel(master, container='false')

This is one of the cases where tk.Tk()  and tk.Toplevel windows differs.
The container property is not supported for the root window.

Regards
Alejandro A.
