### ISSUE TITLE
columnconfigure and rowconfigure are missing

### ISSUE THREAD

**Issue by koutoftimer** [alejandroautalan/pygubu-designer#5]
I haven't found `columnconfigure` and `rowconfigure`.

They are needed for 
https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/tkinter.pdf
> 4.4. Making the root window resizeable

**Comment by alejandroautalan** [comment]
Hi Ruslan, thanks for trying pygubu.

For the main window I recommend you to use the tk.Toplevel widget. This widget already have options for set the window resizable or not. (https://github.com/alejandroautalan/pygubu/wiki/5-Using-the-tk.Toplevel-Widget)

Regarding the columnconfigure and rowconfigure options, you can find them in the layout tab.
They appear as 'Grid row x option' and 'Grid column x option'.

![pygubu-rowcol](https://user-images.githubusercontent.com/3482471/84330583-2983cb00-ab5e-11ea-8816-ee9a648208f5.png)

Regards
Alejandro A.
