### ISSUE TITLE
Setting the font size doesn't work.

### ISSUE THREAD

**Issue by larryw3i** [alejandroautalan/pygubu-designer#53]
Setting the font size doesn't work.

https://user-images.githubusercontent.com/24457116/132977404-998060e8-48b0-41ad-a412-3c676ca15757.mp4

**Comment by alejandroautalan** [comment]
Hello.
Quick repply:
- Yu must Enter a font name like 'helvetica' or select an installed font using the combobox selector.
Then You can change font attributes.

Regards
Alejandro A.

**Comment by larryw3i** [comment]
Thank you, it works now.
