### ISSUE TITLE
Not generating code while using "toplevelmenu" widget

### ISSUE THREAD

**Issue by adbanaei** [alejandroautalan/pygubu-designer#54]
I get this error when I'm using "toplevelmenu" and then press "generate" to produce any kind of code.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Program Files\Python39\lib\site-packages\pygubudesigner\main.py", line 768, in on_code_generate_clicked
    self.script_generator.on_code_generate_clicked()
  File "C:\Program Files\Python39\lib\site-packages\pygubudesigner\scriptgenerator.py", line 107, in on_code_generate_clicked
    code = generator.generate(uidef, target, as_class=True,
  File "C:\Program Files\Python39\lib\site-packages\pygubudesigner\codebuilder.py", line 106, in generate
    self._code_realize(builder, wmeta)
  File "C:\Program Files\Python39\lib\site-packages\pygubudesigner\codebuilder.py", line 228, in _code_realize
    childid = self._code_realize(builder, childmeta)
  File "C:\Program Files\Python39\lib\site-packages\pygubudesigner\codebuilder.py", line 237, in _code_realize
    layout = builder.code_layout(parentid=masterid)
TypeError: code_layout() got an unexpected keyword argument 'parentid'

**Comment by MoeinMavini** [comment]
Hi @alejandroautalan

I looked around the code and in pygubu\builder\tkstdwidgets.py line 955 (class ToplevelMenuHelperBO) code is:

def code_layout(self, targetid=None):
        return tuple()

so no parameter 'parentid' is defined which causes the error.

there are 2 more code_layout functions which have no 'parentid' parameter and 1 that has 'parentid'.

Hope this speeds things up. @MoeinMavini

**Comment by alejandroautalan** [comment]
Hello @adbanaei, thanks for trying pygubu and the bug report.

I will fix it ASAP.

Regards!
Alejandro A.

**Comment by alejandroautalan** [comment]
> Hi @alejandroautalan
> 
> I looked around the code and in pygubu\builder\tkstdwidgets.py line 955 (In class ToplevelMenuHelperBO) code is:
> 
> ```
> def code_layout(self, targetid=None):
>         return tuple()
> ```
> 
> so no parameter 'parentid' is defined which causes the error.
> 
> there are 2 more code_layout functions which have no 'parentid' parameter and 1 that has 'parentid'.

Thansk @MoeinMavini  for the tip.

Regards
Alejandro A.

**Comment by iradraconis** [comment]
I'll add to this issue: when using ttk Toplevel Widget, there is no code generated. 
python: 3.10.4 on darwin
tk: 8.6
pygubu: 0.26
pygubu-designer: 0.31

**Comment by alejandroautalan** [comment]
Hello @iradraconis thanks for trying pygubu.
A new version was uploaded. Try again reinstalling pygubu-designer with:

    pip install --upgrade pygubu-designer

If the issue persist, open a new issue, and provide a minimal UI file to re-create the bug.

Regards.

**Comment by iradraconis** [comment]
After updating, it works again! Thank you for that immediate fix!
