### ISSUE TITLE
Missing import when using "scrolledframe" and generating code script

### ISSUE THREAD

**Issue by adbanaei** [alejandroautalan/pygubu-designer#55]
When I'm using "scrolledframe" and generating code script, there's a missing import. I managed to add it with this:

from pygubu.builder.widgets.scrolledframe import ScrolledFrame

It would be nice if this included into generated script.

**Comment by alejandroautalan** [comment]
Hello @adbanaei, thanks for the bug report.

I will fix it ASAP.

Regards!
Alejandro A.
