### ISSUE TITLE
Menu Problem while using script generator

### ISSUE THREAD

**Issue by adbanaei** [alejandroautalan/pygubu-designer#57]
Hey there,
1. Menu command callback is not adding properly, instead a method named "command" is added.
2. When using menu and submenu together, index numbers are incorrect. For example after I use 6 submenus and 1 command under toplevel menu, index of all 6 are 0 and last command becomes 1.
3. In class, submenus and index numbers don't have "self." thus can't be used when inheriting.

**Comment by alejandroautalan** [comment]
Hello @adbanaei , thanks for trying pygubu and the bug report.

I was able to reproduce the error and I will fix it as soon as possible.

Regards
Alejandro A.

**Comment by alejandroautalan** [comment]
Hello, I can't reproduce this:
> Hey there,
>     2. When using menu and submenu together, index numbers are incorrect. For example after I use 6 submenus and 1 command under toplevel menu, index of all 6 are 0 and last command becomes 1.

Take note that the index generated is a helper to connect the callback later.  If you modify the menu at runtime (adding or deleting new items) the index of each item might change.
Also, the index matches the position of the item in its parent menu. If the menu has the tearoff = False, index starts in 0.

I will upload a fix. Let me know if all problems are corrected.

Regards.
Alejandro A.
