### ISSUE TITLE
Shortcut bindings failure on some keyboard layouts

### ISSUE THREAD

**Issue by ObaraEmmanuel** [alejandroautalan/pygubu-designer#7]
Shortcut bindings such as Ctrl+x for cutting do not work in other keyboard layouts such as Russian. This is because the modifiers used rely on keysym attribute of the tkinter event  which would be 'x' in English layout but 'ч' in Russian layout. Now, notice that Russian is just an example I am using and which I have also managed to reproduce the issue with. Therefore, this issue could potentially affect countless Keyboard layouts causing shortcut bindings to fail in unpredictable ways. My recommendation is a manual  key event dispatch system that uses keycode instead of keysym to bind these events. For instance 'x' and 'ч' will always have the same keycode 88; this applies to anything using the physical key 'x' regardless of the keyboard layout.

**Comment by alejandroautalan** [comment]
Hello Emmanuel, thanks for trying pygubu and for your report.
I did not realize that this could happen.
I will try to correct it as soon as possible.

Regards
Alejandro A.

**Comment by ObaraEmmanuel** [comment]
Funny enough even IDLE suffers from this flaw. After switching to Russian layout cut-copy-paste ceases to function!
