### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by sumeshir26** [alejandroautalan/pygubu-designer#73]
Hi, I reallay like this project and want to contribute but am unsure hot to build. Can anyone pls help me?
Thanks!

**Comment by rdbende** [comment]
1. Clone the repository
2. Create a virtual environment in the repo root, activate it and install the requirements
3. Run `python3 -m pygubudesigner` (or `py -m pygubudesigner` if you are on Windows) in the terminal to run the designer

**Comment by larryw3i** [comment]
run  
```bash
python3 setup.py sdist bdist_wheel
```  
in the repo root, .whl file will be generated.

**Comment by sumeshir26** [comment]
Thanks @larryw3i and @rdbende

**Comment by sumeshir26** [comment]
> 

@rdbende I get this error: 
![image](https://user-images.githubusercontent.com/68823982/149062423-a4726a82-e52d-426a-b1aa-51a36640693e.png)

**Comment by alejandroautalan** [comment]
Hello @sumeshir26, thanks for trying pygubu.
It seems that you are on a Windows environment.
Try the following instructions (you will need **git** and **git-bash** console installed)

```bash
# Open a **GitBash** console:
# Right click on Desktop (or the folder you want), Click open GitBash here.

# This is the python version installed here
$ python --version
Python 3.8.5

# Create a project folder
mkdir mypygubu-project
cd mypygubu-project

# Create a virtual environment called venv
python -m venv venv

# activate virtual environment
source ./venv/Scripts/activate

# clone pygubu-designer repository
git clone https://github.com/alejandroautalan/pygubu-designer.git

# Change to pygubu-designer folder, and install it in developer mode
cd pygubu-designer
pip install -e ./

# generate PO files for developer mode
./pygubudesigner.sh msgf

# Run designer
python -m pygubudesigner
```

Let me know.
Regards
Alejandro A.

**Comment by alejandroautalan** [comment]
I will add a wiki page with this information.
