### ISSUE TITLE
Add support to configure grid using 'all' index

### ISSUE THREAD

**Issue by alejandroautalan** [alejandroautalan/pygubu-designer#76]
To improve grid layout manager configuration I want to add support to configure the grid with the 'all' index.

This will require:

- new container layout editor
- change xml specification. This includes reorganization of grid_rc properties.
- Separate widget layout options in child options and container options (the available options when widget is acting as a container)
- Child grid options: row, column, sticky, rowspan, columnspan, padx,  pady, ipadx, ipady
- Container grid options: anchor, propagate
- The actual grid propagate option moved to the container options. For example: Currently the propagate option set on children does not work when the container is packed and his children gridded.

Example of the new xml:

```xml
<object class="ttk.Frame" id="frame1">
    <property name="height">200</property>
    <property name="width">200</property>
    <layout manager="pack">
        <property name="side">top</property>
    </layout>
    <containerlayout manager="grid">
        <property name="propagate">True</property>
        <property name="anchor">se</property>
        <property type="col" id="0" name="pad">15</property>
        <property type="row" id="0" name="pad">10</property>
        <property type="col" id="all" name="pad">50</property>
        <property type="col" id="all" name="weight">0</property>
        <property type="row" id="all" name="pad">10</property>
        <property type="row" id="all" name="weight">0</property>
      </containerlayout>
</object>
```

**Comment by jrezai** [comment]
Hi @alejandroautalan ,

What is the 'all' index? I've never heard of it. Is it related to something that tkinter supports via grid or is it something else?
When should the 'all' index be used?

Thanks.

**Comment by alejandroautalan** [comment]
Hello @jrezai,
It's a grid manager option. You can pass 'all' to the **rowconfigure** and **columnconfigure** methods.
For example, if you have a frame with a grid of 10x10 children and you want a pad separation of 20 between each widget:

    frame.rowconfigure('all', pad=20)
    frame.columnconfigure('all', pad=20)

If you want to do the same with the designer you need to configure each row and column with pad=20.
The new container layout editor will solve this.
A quick screenshot of the new editor:

![container_editor](https://user-images.githubusercontent.com/3482471/150467753-33f2ae5e-38da-4ec6-baa2-1a6c858d8caa.png)


Regards
Alejandro A.

**Comment by jrezai** [comment]
That sounds great, thanks for the explanation.
