### ISSUE TITLE
Cannot launch Ubuntu 20.04

### ISSUE THREAD

**Issue by newmonte** [alejandroautalan/pygubu-designer#81]
Think I'm missing something simple, have already compiled the .po files but still getting this error ?

You should compile the .po files in the pygubudesigner/locale directory first

Thanks

**Comment by jrezai** [comment]
Hello,
Try compiling the .po files for _all_ the provided languages in the pygubudesigner folder.
For example, in: `/locale/de` and `/locale/es` and `/locale/tr`

The command will look something like this, in each of the locale/language folders:
> msgfmt -o pygubu.mo pygubu.po

I hope that helps.

**Comment by newmonte** [comment]
Thanks
Had already done that, but did it again, still same message on launch, also used the makepofile.sh with same result, then tried poedit, still no joy.

**Comment by newmonte** [comment]
Got it now, thankyou, pip uninstalled and re install fixed it. Thanks again.
