### ISSUE TITLE
more intuitive design screen labels

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#87]
Regarding the [design screen](https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Screen) wiki page. Could pygubu-designer be more intuitive and the need for adding red boxes and labels on the screen-shot eliminated? How do you feel about:

1. changing 'Object Tree' to 'Tree,'

2. changing 'Object Property' to 'Properties,'

3. changing 'Widget Id to 'Id,'

4. adding a header to the preview pane that is labelled 'Preview,'

5. in the General tab, eliminating the 'Widget properties' label and the bounding box it is part of,

6. in the Layout tab eliminating the 'Options:' label and the bounding box it is part of,

7. in the Properties pane, rename the 'General' tab to something more descriptive, such as 'Look' or 'Appearance,'

8. putting a fresh screen-shot on the wiki page,

9. and, changing the wording throughout the wiki to use the phrasing Tree, Properties, or Preview pane?

**Comment by alejandroautalan** [comment]
Fixed in 80d86f41bd94f0eb613c8eadaf99763c61129f77.  Needs wiki update before 0.25 release
