### ISSUE TITLE
Custom widget code generation error

### ISSUE THREAD

**Issue by skyice78** [alejandroautalan/pygubu-designer#9]
The python code generated for ttk.Notebook automatically added 'self' to the id causing the error. 

Attached is the screen shot of the ttk.Notebook setup and auto generated code. 

![pygubu-designer error](https://user-images.githubusercontent.com/8575769/93235334-03645d00-f743-11ea-8e84-d5d26a30ea90.JPG)

![pygubu-designer error 1](https://user-images.githubusercontent.com/8575769/93235507-46becb80-f743-11ea-8e95-37fe78817dd5.JPG)

**Comment by alejandroautalan** [comment]
Hi skyice78, thanks for trying pygubu and the bug report.
I will fixit ASAP.

Regards
Alejandro A.

**Comment by alejandroautalan** [comment]
Fixed on last release.
