### ISSUE TITLE
perhaps the Generate button can be removed

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#90]
The code generates so quickly can the Generate button be removed; it would eliminate a step for the user?

Perhaps the code could be generated whenever the code tab is pushed or an option within the code tab changes.

If sometimes code generation takes a noticeable about of time, then perhaps the preview pane could be temporarily be replaced with a 'code generation' progress bar.

If you do this, update [this](https://github.com/alejandroautalan/pygubu-designer/wiki/Code-Generator-Screen) the wiki page.

**Comment by alejandroautalan** [comment]
Code tab removed. User can configure project options and generate code on save.  Fixed in v0.39
