### ISSUE TITLE
try except on import?

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#94]
In some example code, I noticed the following.

```
try:
    import tkinter as tk
except:
    import Tkinter as tk
```

Should the code generator be doing that?

**Comment by rdbende** [comment]
In my opinion **not**.
It's just for compatibility with Python 2, but since it reached End of Life in January 2020, and new code shouldn't support it. Especially because Pygubu wants to drop Python 2 support (#75)

**Comment by alejandroautalan** [comment]
> In some example code, I noticed the following.
> 
> ```
> try:
>     import tkinter as tk
> except:
>     import Tkinter as tk
> ```
> 
> Should the code generator be doing that?

Hello Peter,
Those examples were created manually, before the code generator existed in the designer.
The code generator always creates python3 code.
I will update and remove python 2 stuff.

Regards
Alejandro A.
