### ISSUE TITLE
finish Custom Widget

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#95]
Python 2 is obsolete and that is what the Custom Widget options handled.

**Comment by alejandroautalan** [comment]
Hello,
Custom Widget in the code generation is not related to python 2.
Its for advanced users. This area allows you to create your own compound widgets, and (in the future) will create the required classes to incorporate the widget in the designer palette. Development in this area is not completed.
At the moment you can add your custom widgets to the designer palette, but its a manual process. The custom widget area will make this process easy.

Regards
Alejandro A.

**Comment by matecsaj** [comment]
Thank you for the Custom Widget correction. 

Does this belong with the Custom Widget documentation? Is it the **_manual process_** for completing a Custom Widget?
https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse

**Comment by alejandroautalan** [comment]
> Thank you for the Custom Widget correction.
> 
> Does this belong with the Custom Widget documentation? Is it the **_manual process_** for completing a Custom Widget? https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse

Yes it is.  I will try to complete the documentation also.

**Comment by matecsaj** [comment]
As an interim documentation measure, I removed https://github.com/alejandroautalan/pygubu-designer/wiki/Design-Reuse from the wiki's TOC and linked to it from the Customer Widget section in https://github.com/alejandroautalan/pygubu-designer/wiki/Code-Generator-Screen.

**Comment by alejandroautalan** [comment]
Custom widget template usable now. Fixed in v0.39
